### ISSUE TITLE
NullPointerException in DocumentVectors

### ISSUE THREAD

**Issue by PhMeier** [chungkwong/text-classifier-collection#2]
Hello,
i receive the following stack trace: (Code is similar to Demo.java)

Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:897)
	at com.github.chungkwong.classifier.DocumentVectorsModel.lambda$21(DocumentVectorsModel.java:83)
	at java.base/java.util.HashMap.forEach(HashMap.java:1341)
	at com.github.chungkwong.classifier.DocumentVectorsModel.retainAll(DocumentVectorsModel.java:75)
	at com.github.chungkwong.classifier.BagClassifierFactory.getClassifier(BagClassifierFactory.java:48)
	at com.github.chungkwong.classifier.BagClassifierFactory.getClassifier(BagClassifierFactory.java:1)
	at com.github.chungkwong.classifier.PreprocessClassifierFactory.getClassifier(PreprocessClassifierFactory.java:41)
	at SvmTelekom.main(SvmTelekom.java:66)

In the DocumentVectorsModel file, changing the method "retainAll(Set<T> toKeep)" to this:

	@Override
	public void retainAll(Set<T> toKeep){
		getProfiles().forEach((k,v)->{
			if(k == null) System.out.println("k=null");
			List<Frequencies<T>> documentVectors = v.getDocumentVectors();
			if(documentVectors == null) System.err.println("v=null");
			System.out.println(k+"="+v);
			int i=0;
			Iterator<Frequencies<T>> iter = documentVectors.iterator();
			while (iter.hasNext()) {
				Frequencies<T> vector = iter.next();
				if(vector == null) System.out.println("Error");
				else System.out.println("v"+(i++)+"+"+vector);
			}
			documentVectors.forEach((vector)->vector.toMap().keySet().retainAll(toKeep));
		});
	}

does not solve the issue.
Even though using the iterators .hasNext() method, the method is throwing a NullPointerException. All this happens sporadic, sometimes the code runs through without any exceptions.
I'm using eclipse with Java 10.

**Comment by chungkwong** [comment]
Are you using multiple threads?

**Comment by PhMeier** [comment]
No, i'm not using multiple threads. 
If I read the training data file by file(instead of a .csv) the error does not appear.

**Comment by chungkwong** [comment]
Are you sure that all lines of the CSV file contain the two fields specified? In particular, no empty line before the end of file.

**Comment by PhMeier** [comment]
I checked the CSV and could not find any empty fields or lines.
In my opinion, something goes wrong during training.
I've attached the debugger output, as you can see, "documentVectors" and the model vectors contain null values.
![ChungModelOutput](https://user-images.githubusercontent.com/48480765/59111478-67458680-8941-11e9-95e1-9414edfbc033.PNG)
![ChungDocumentVectors](https://user-images.githubusercontent.com/48480765/59111481-690f4a00-8941-11e9-8570-286b342eae34.PNG)

**Comment by chungkwong** [comment]
Have you used  a customized preprocessor that can return null?

**Comment by PhMeier** [comment]
At the moment i'm not using a pretokenizer, my code looks like this:

	public static void main(String[] args) throws IOException {
		
		// read in stop words
		String[] stopwords = readDatafromFile("src/main/resources/german_stopwords.txt");
		List<String> stopw = Arrays.asList(stopwords);
		// First, create a classifier
		SvmClassifierFactory baseClassifierFactory = new SvmClassifierFactory();
		//System.out.println(baseClassifierFactory.getTfIdfFormula());
		// select features using Tf-Idf
		TfIdfFeatureSelector tf = new TfIdfFeatureSelector(5000);
		baseClassifierFactory.setFeatureSelector(tf);
		
		
		//Function<String, String> preTokenize = TextPreprocessors.getIcuTransformer("german");
		//Function<String, Stream<String>> tokenizer = TextPreprocessors.getIcuTokenizer(BreakIterator.getWordInstance(Locale.GERMAN));
		
		Function<String, Stream<String>> tokenizer = TextPreprocessors.getJavaTokenizer(BreakIterator.getWordInstance(Locale.GERMAN)); //getCharacterInstance(Locale.GERMAN)
		// Create a tokenizer, the following one remove white space and then generate 2-gram
		Function<Stream<String>, Stream<String>> postTokenize = TextPreprocessors.getStopWordsFilter(stopw)
																.compose(TextPreprocessors.getWhitespaceFilter())
																.compose(TextPreprocessors.getDowncaser())
																.andThen(TextPreprocessors.getNgramGenerator(1,2));
																//.compose(TextPreprocessors.getNgramGenerator(1));
																//.compose(TextPreprocessors.getNgramGenerator(3));
		// Create a text ClassifierFactory with given preprocessors applied
		PreprocessClassifierFactory<FrequenciesModel<String>, String, Frequencies<String>> classifierFactory = new PreprocessClassifierFactory(
				TextPreprocessors.of(tokenizer, postTokenize), baseClassifierFactory);
		PreprocessModel<FrequenciesModel<String>, String, Frequencies<String>> model = classifierFactory.createModel(); 
		model.train(TextDatasetHelper.csvRecords(new File(DATA).toPath(), 1, 0));
		//model.getUnderlying().getTokenCounts();
		Classifier<String> classifier = classifierFactory.getClassifier(model);
	}

If I use the the ICUTransformer as pretokenizer, i'll get the same behaviour, the NPE appears sporadic.

**Comment by chungkwong** [comment]
Thank you very much for providing code to reproduce the NullPointerException. It turns out that there is a bug in the CSV parser, the bug is fixed in the latest commit.

**Comment by PhMeier** [comment]
Great, thank you very much!
